name: Version Bump

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - run: npm ci

      - name: Bump version and push tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          npm version patch -m "chore: release %s [skip ci]"
          git push origin HEAD:main --follow-tags

      # Optional: generate changelog and GitHub release
      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
