name: Version Bump (on merge to main)

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write

concurrency:
  group: version-bump-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main with full history + tags
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Configure git as the bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Make sure we’re on the latest main before we create a new commit
      - name: Sync with origin/main
        run: |
          git fetch --tags origin main
          git checkout main
          git pull --rebase origin main

      - name: Bump patch, create tag, and push
        env:
          # Optional: skip CI on the bump commit so this workflow doesn't retrigger anything else
          SKIP_CI: "[skip ci]"
        run: |
          # npm version updates package.json (+ lockfile), commits, and creates an annotated tag vX.Y.Z
          npm version patch -m "chore: release %s $SKIP_CI"
          # Push commit and the new tag
          git push origin main --follow-tags
